export const locales = ['en', 'es', 'ar'] as const;
export type Locale = (typeof locales)[number];

export const languageOptions: { value: Locale; label: string }[] = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español' },
  { value: 'ar', label: 'العربية' },
];

// Edit this file to update every public-facing translation in one place.
export const messages: Record<Locale, Record<string, string>> = {
  en: {
    'nav.home': 'Home', 'nav.products': 'Products', 'nav.about': 'About Us', 'nav.contact': 'Contact Us', 'nav.quote': 'Request Quote', 'nav.language': 'Language',
    'home.eyebrow': 'Global sourcing, simplified', 'home.title': 'Small appliances made for your market.', 'home.copy': 'Quality-focused OEM and wholesale solutions for European and Middle Eastern buyers.', 'home.explore': 'Explore products',
    'home.featuredEyebrow': 'Featured collection', 'home.featuredTitle': 'Everyday products, elevated.', 'home.viewAll': 'View all products',
    'home.partnerEyebrow': 'A dependable export partner', 'home.partnerTitle': 'Built for long-term retail relationships.', 'home.partnerCopy': 'We support private-label buyers, distributors and retailers with clear communication, quality-led sourcing and practical delivery planning.', 'home.facts': '12+ years export experience · Europe & Middle East · OEM support',
    'home.ctaEyebrow': "Let's talk sourcing", 'home.ctaTitle': 'Need a product range that fits your market?', 'home.ctaButton': 'Request a quotation',
    'products.eyebrow': 'Product collection', 'products.title': 'Products ready to perform.', 'products.copy': 'Kitchen, home and personal-care essentials for international retail.', 'products.all': 'All products', 'products.kitchen': 'Kitchen', 'products.home': 'Home', 'products.personal': 'Personal Care',
    'product.view': 'View specifications', 'product.moq': 'MOQ', 'product.price': 'FOB price', 'product.back': 'Back to products', 'product.galleryEyebrow': 'Product gallery', 'product.galleryTitle': 'Designed for coffee anywhere.', 'product.specs': 'Specifications', 'product.overview': 'Product overview', 'product.colours': 'Available colours', 'product.packaging': 'Packaging & logistics', 'product.ready': 'Ready for export.', 'product.packagingCopy': 'Standard export carton packing is available. Our team can support inspection, loading and shipping documentation according to your destination.', 'product.sendInquiry': 'Send product inquiry', 'product.askWhatsapp': 'Ask on WhatsApp', 'product.emailInquiry': 'Email inquiry', 'product.whatsappMessage': 'Hello, I am interested in', 'product.brandingCopy': 'Custom branding, colour and packaging options are available for qualified orders.',
    'contact.eyebrow': 'Contact us', 'contact.title': "Let's start a conversation.", 'contact.copy': 'Tell us your sourcing requirements and our export team will respond within one business day.', 'contact.direct': 'Reach us directly', 'contact.fastQuote': 'For a faster quotation, include your target market, desired quantity and product category.', 'contact.formEyebrow': 'Send an inquiry', 'contact.name': 'Your name', 'contact.email': 'Business email', 'contact.company': 'Company', 'contact.request': 'Your request', 'contact.prepare': 'Prepare email inquiry', 'contact.note': 'Your email application will open with this inquiry ready to send.', 'contact.requestPlaceholder': 'Products, quantity, destination and custom needs...',
    'about.eyebrow': 'About Ningbo Shanwu', 'about.title': 'A practical partner for global sourcing.', 'about.copy': 'We help international buyers source dependable small appliances with responsive communication, export-ready documentation and flexible OEM support.', 'about.factoryTitle': 'Factory capability', 'about.factoryCopy': 'Quality-focused supplier coordination for kitchen, home and personal-care appliance programs.', 'about.marketTitle': 'Markets we serve', 'about.marketCopy': 'Europe · Middle East · Global retail', 'about.certTitle': 'Export support', 'about.certCopy': 'Packaging, inspection coordination and shipping documentation tailored to your destination.',
    'footer.tagline': 'Small appliances for global retail.', 'footer.contact': 'Contact us', 'footer.whatsapp': 'WhatsApp', 'category.Kitchen': 'Kitchen', 'category.Home': 'Home', 'category.Personal Care': 'Personal Care',
    'catalog.digital-air-fryer.name': 'Digital Air Fryer', 'catalog.digital-air-fryer.description': '5.5L capacity and intuitive touch controls for modern family kitchens.', 'catalog.steel-kettle.name': 'Stainless Steel Kettle', 'catalog.steel-kettle.description': 'Fast-boil cordless kettle with a refined, durable steel body.', 'catalog.ceramic-steam-iron.name': 'Ceramic Steam Iron', 'catalog.ceramic-steam-iron.description': 'Smooth-glide ceramic soleplate with dependable steam performance.', 'catalog.portable-espresso-maker.name': 'Portable 20-Bar Espresso Maker', 'catalog.portable-espresso-maker.description': 'Compact USB-rechargeable espresso maker with 20-bar extraction, designed for office, home and travel use. Compatible with coffee capsules and ground coffee for hot or cold brewing.', 'catalog.ionic-hair-dryer.name': 'Ionic Hair Dryer', 'catalog.ionic-hair-dryer.description': 'Salon-inspired, low-noise drying with ionic technology.',
    'spec.Capacity': 'Capacity', 'spec.Power': 'Power', 'spec.Voltage': 'Voltage', 'spec.Branding': 'Branding', 'spec.Soleplate': 'Soleplate', 'spec.Motor': 'Motor', 'spec.Pump pressure': 'Pump pressure', 'spec.Coffee compatibility': 'Coffee compatibility', 'spec.Brewing mode': 'Brewing mode', 'spec.Body material': 'Body material', 'spec.Rated voltage': 'Rated voltage', 'spec.Charging': 'Charging', 'spec.Product size': 'Product size', 'spec.Gross weight': 'Gross weight',
    'value.OEM available': 'OEM available', 'value.OEM / private label available': 'OEM / private label available', 'value.Capsules and ground coffee': 'Capsules and ground coffee', 'value.Hot and cold extraction': 'Hot and cold extraction', 'value.Plastic': 'Plastic', 'value.USB-C, approx. 4 hours': 'USB-C, approx. 4 hours', 'colour.Black': 'Black', 'colour.Silver Gray': 'Silver Gray', 'colour.Olive Green': 'Olive Green', 'colour.Pink': 'Pink', 'colour.Dark Green': 'Dark Green', 'colour.Light Purple': 'Light Purple',
  },
  es: {
    'nav.home': 'Inicio', 'nav.products': 'Productos', 'nav.about': 'Quiénes somos', 'nav.contact': 'Contáctenos', 'nav.quote': 'Solicitar cotización', 'nav.language': 'Idioma',
    'home.eyebrow': 'Abastecimiento global, simplificado', 'home.title': 'Pequeños electrodomésticos para su mercado.', 'home.copy': 'Soluciones OEM y mayoristas centradas en la calidad para compradores de Europa y Oriente Medio.', 'home.explore': 'Ver productos',
    'home.featuredEyebrow': 'Colección destacada', 'home.featuredTitle': 'Productos cotidianos, mejorados.', 'home.viewAll': 'Ver todos los productos',
    'home.partnerEyebrow': 'Un socio de exportación fiable', 'home.partnerTitle': 'Relaciones comerciales a largo plazo.', 'home.partnerCopy': 'Apoyamos a compradores de marca privada, distribuidores y minoristas con comunicación clara, abastecimiento orientado a la calidad y planificación práctica de entregas.', 'home.facts': 'Más de 12 años de exportación · Europa y Oriente Medio · Soporte OEM',
    'home.ctaEyebrow': 'Hablemos de abastecimiento', 'home.ctaTitle': '¿Necesita una gama de productos para su mercado?', 'home.ctaButton': 'Solicitar cotización',
    'products.eyebrow': 'Colección de productos', 'products.title': 'Productos listos para rendir.', 'products.copy': 'Artículos de cocina, hogar y cuidado personal para el comercio internacional.', 'products.all': 'Todos los productos', 'products.kitchen': 'Cocina', 'products.home': 'Hogar', 'products.personal': 'Cuidado personal',
    'product.view': 'Ver especificaciones', 'product.moq': 'MOQ', 'product.price': 'Precio FOB', 'product.back': 'Volver a productos', 'product.galleryEyebrow': 'Galería de producto', 'product.galleryTitle': 'Café para cualquier lugar.', 'product.specs': 'Especificaciones', 'product.overview': 'Resumen del producto', 'product.colours': 'Colores disponibles', 'product.packaging': 'Embalaje y logística', 'product.ready': 'Listo para exportar.', 'product.packagingCopy': 'Hay embalaje estándar para exportación. Nuestro equipo puede apoyar con inspección, carga y documentación de envío según su destino.', 'product.sendInquiry': 'Enviar consulta', 'product.askWhatsapp': 'Consultar por WhatsApp', 'product.emailInquiry': 'Consulta por correo', 'product.whatsappMessage': 'Hola, me interesa', 'product.brandingCopy': 'Hay opciones de marca, color y embalaje personalizados para pedidos cualificados.',
    'contact.eyebrow': 'Contáctenos', 'contact.title': 'Iniciemos una conversación.', 'contact.copy': 'Indique sus requisitos de compra y nuestro equipo de exportación responderá en un día hábil.', 'contact.direct': 'Contacto directo', 'contact.fastQuote': 'Para una cotización más rápida, incluya su mercado, cantidad deseada y categoría de producto.', 'contact.formEyebrow': 'Enviar una consulta', 'contact.name': 'Su nombre', 'contact.email': 'Correo empresarial', 'contact.company': 'Empresa', 'contact.request': 'Su solicitud', 'contact.prepare': 'Preparar correo de consulta', 'contact.note': 'Su aplicación de correo se abrirá con esta consulta lista para enviar.', 'contact.requestPlaceholder': 'Productos, cantidad, destino y necesidades de personalización...',
    'about.eyebrow': 'Sobre Ningbo Shanwu', 'about.title': 'Un socio práctico para el abastecimiento global.', 'about.copy': 'Ayudamos a compradores internacionales a abastecer pequeños electrodomésticos fiables con comunicación ágil, documentación de exportación y soporte OEM flexible.', 'about.factoryTitle': 'Capacidad de fábrica', 'about.factoryCopy': 'Coordinación de proveedores enfocada en calidad para programas de cocina, hogar y cuidado personal.', 'about.marketTitle': 'Mercados atendidos', 'about.marketCopy': 'Europa · Oriente Medio · Comercio global', 'about.certTitle': 'Soporte de exportación', 'about.certCopy': 'Embalaje, coordinación de inspección y documentación de envío adaptados a su destino.',
    'footer.tagline': 'Pequeños electrodomésticos para el comercio global.', 'footer.contact': 'Contáctenos', 'footer.whatsapp': 'WhatsApp', 'category.Kitchen': 'Cocina', 'category.Home': 'Hogar', 'category.Personal Care': 'Cuidado personal',
    'catalog.digital-air-fryer.name': 'Freidora de aire digital', 'catalog.digital-air-fryer.description': 'Capacidad de 5,5 L y controles táctiles intuitivos para cocinas familiares modernas.', 'catalog.steel-kettle.name': 'Hervidor de acero inoxidable', 'catalog.steel-kettle.description': 'Hervidor inalámbrico de ebullición rápida con cuerpo de acero refinado y resistente.', 'catalog.ceramic-steam-iron.name': 'Plancha de vapor cerámica', 'catalog.ceramic-steam-iron.description': 'Suela cerámica de deslizamiento suave con rendimiento de vapor fiable.', 'catalog.portable-espresso-maker.name': 'Cafetera espresso portátil de 20 bares', 'catalog.portable-espresso-maker.description': 'Cafetera espresso compacta recargable por USB con extracción de 20 bares para oficina, hogar y viajes. Compatible con cápsulas y café molido para preparación fría o caliente.', 'catalog.ionic-hair-dryer.name': 'Secador de cabello iónico', 'catalog.ionic-hair-dryer.description': 'Secado silencioso de inspiración profesional con tecnología iónica.',
    'spec.Capacity': 'Capacidad', 'spec.Power': 'Potencia', 'spec.Voltage': 'Voltaje', 'spec.Branding': 'Marca', 'spec.Soleplate': 'Suela', 'spec.Motor': 'Motor', 'spec.Pump pressure': 'Presión de la bomba', 'spec.Coffee compatibility': 'Compatibilidad de café', 'spec.Brewing mode': 'Modo de preparación', 'spec.Body material': 'Material del cuerpo', 'spec.Rated voltage': 'Voltaje nominal', 'spec.Charging': 'Carga', 'spec.Product size': 'Tamaño del producto', 'spec.Gross weight': 'Peso bruto',
    'value.OEM available': 'OEM disponible', 'value.OEM / private label available': 'OEM / marca privada disponible', 'value.Capsules and ground coffee': 'Cápsulas y café molido', 'value.Hot and cold extraction': 'Extracción fría y caliente', 'value.Plastic': 'Plástico', 'value.USB-C, approx. 4 hours': 'USB-C, aprox. 4 horas', 'colour.Black': 'Negro', 'colour.Silver Gray': 'Gris plateado', 'colour.Olive Green': 'Verde oliva', 'colour.Pink': 'Rosa', 'colour.Dark Green': 'Verde oscuro', 'colour.Light Purple': 'Violeta claro',
  },
  ar: {
    'nav.home': 'الرئيسية', 'nav.products': 'المنتجات', 'nav.about': 'من نحن', 'nav.contact': 'اتصل بنا', 'nav.quote': 'اطلب عرض سعر', 'nav.language': 'اللغة',
    'home.eyebrow': 'توريد عالمي بطريقة أبسط', 'home.title': 'أجهزة منزلية صغيرة تناسب سوقك.', 'home.copy': 'حلول تصنيع OEM وبيع بالجملة تركز على الجودة لعملاء أوروبا والشرق الأوسط.', 'home.explore': 'استكشف المنتجات',
    'home.featuredEyebrow': 'مجموعة مختارة', 'home.featuredTitle': 'منتجات يومية بمستوى أعلى.', 'home.viewAll': 'عرض جميع المنتجات',
    'home.partnerEyebrow': 'شريك تصدير موثوق', 'home.partnerTitle': 'مصمم لعلاقات تجارية طويلة الأمد.', 'home.partnerCopy': 'ندعم مشتري العلامات الخاصة والموزعين وتجار التجزئة بتواصل واضح وتوريد قائم على الجودة وتخطيط عملي للتسليم.', 'home.facts': 'أكثر من 12 عاماً في التصدير · أوروبا والشرق الأوسط · دعم OEM',
    'home.ctaEyebrow': 'لنتحدث عن التوريد', 'home.ctaTitle': 'هل تحتاج إلى مجموعة منتجات تناسب سوقك؟', 'home.ctaButton': 'اطلب عرض سعر',
    'products.eyebrow': 'مجموعة المنتجات', 'products.title': 'منتجات جاهزة للأداء.', 'products.copy': 'أساسيات المطبخ والمنزل والعناية الشخصية للبيع بالتجزئة عالمياً.', 'products.all': 'كل المنتجات', 'products.kitchen': 'المطبخ', 'products.home': 'المنزل', 'products.personal': 'العناية الشخصية',
    'product.view': 'عرض المواصفات', 'product.moq': 'الحد الأدنى للطلب', 'product.price': 'سعر FOB', 'product.back': 'العودة إلى المنتجات', 'product.galleryEyebrow': 'معرض المنتج', 'product.galleryTitle': 'قهوة في أي مكان.', 'product.specs': 'المواصفات', 'product.overview': 'نظرة عامة على المنتج', 'product.colours': 'الألوان المتاحة', 'product.packaging': 'التعبئة والخدمات اللوجستية', 'product.ready': 'جاهز للتصدير.', 'product.packagingCopy': 'يتوفر تغليف كرتوني قياسي للتصدير. يدعم فريقنا الفحص والتحميل ووثائق الشحن وفقاً لوجهتك.', 'product.sendInquiry': 'إرسال استفسار', 'product.askWhatsapp': 'اسأل عبر واتساب', 'product.emailInquiry': 'استفسار عبر البريد', 'product.whatsappMessage': 'مرحباً، أنا مهتم بـ', 'product.brandingCopy': 'تتوفر خيارات العلامة التجارية والألوان والتغليف المخصص للطلبات المؤهلة.',
    'contact.eyebrow': 'اتصل بنا', 'contact.title': 'لنبدأ محادثة.', 'contact.copy': 'أخبرنا بمتطلبات التوريد وسيرد فريق التصدير خلال يوم عمل واحد.', 'contact.direct': 'تواصل معنا مباشرة', 'contact.fastQuote': 'للحصول على عرض أسرع، أدرج السوق المستهدف والكمية المطلوبة وفئة المنتج.', 'contact.formEyebrow': 'أرسل استفساراً', 'contact.name': 'الاسم', 'contact.email': 'البريد الإلكتروني للشركة', 'contact.company': 'الشركة', 'contact.request': 'طلبك', 'contact.prepare': 'إعداد استفسار بالبريد', 'contact.note': 'سيفتح تطبيق البريد الإلكتروني مع الاستفسار جاهزاً للإرسال.', 'contact.requestPlaceholder': 'المنتجات والكمية والوجهة واحتياجات التخصيص...',
    'about.eyebrow': 'عن نينغبو شان وو', 'about.title': 'شريك عملي للتوريد العالمي.', 'about.copy': 'نساعد المشترين الدوليين على توريد أجهزة منزلية صغيرة موثوقة عبر تواصل سريع ووثائق تصدير ودعم OEM مرن.', 'about.factoryTitle': 'قدرات المصنع', 'about.factoryCopy': 'تنسيق موردين يركز على الجودة لبرامج أجهزة المطبخ والمنزل والعناية الشخصية.', 'about.marketTitle': 'الأسواق التي نخدمها', 'about.marketCopy': 'أوروبا · الشرق الأوسط · تجارة التجزئة العالمية', 'about.certTitle': 'دعم التصدير', 'about.certCopy': 'تغليف وتنسيق فحص ووثائق شحن مخصصة لوجهتك.',
    'footer.tagline': 'أجهزة منزلية صغيرة لتجارة التجزئة العالمية.', 'footer.contact': 'اتصل بنا', 'footer.whatsapp': 'واتساب', 'category.Kitchen': 'المطبخ', 'category.Home': 'المنزل', 'category.Personal Care': 'العناية الشخصية',
    'catalog.digital-air-fryer.name': 'قلاية هوائية رقمية', 'catalog.digital-air-fryer.description': 'سعة 5.5 لتر وتحكم باللمس سهل الاستخدام للمطابخ العائلية الحديثة.', 'catalog.steel-kettle.name': 'غلاية من الفولاذ المقاوم للصدأ', 'catalog.steel-kettle.description': 'غلاية لاسلكية سريعة الغليان بهيكل فولاذي أنيق ومتين.', 'catalog.ceramic-steam-iron.name': 'مكواة بخار بسـطح سيراميكي', 'catalog.ceramic-steam-iron.description': 'سطح سيراميكي سهل الانزلاق مع أداء بخار موثوق.', 'catalog.portable-espresso-maker.name': 'ماكينة إسبرسو محمولة بضغط 20 بار', 'catalog.portable-espresso-maker.description': 'ماكينة إسبرسو مدمجة قابلة للشحن عبر USB بضغط استخلاص 20 بار، مناسبة للمكتب والمنزل والسفر، ومتوافقة مع الكبسولات والقهوة المطحونة للتحضير الساخن أو البارد.', 'catalog.ionic-hair-dryer.name': 'مجفف شعر أيوني', 'catalog.ionic-hair-dryer.description': 'تجفيف هادئ مستوحى من الصالونات بتقنية الأيونات.',
    'spec.Capacity': 'السعة', 'spec.Power': 'القدرة', 'spec.Voltage': 'الجهد', 'spec.Branding': 'العلامة التجارية', 'spec.Soleplate': 'سطح المكواة', 'spec.Motor': 'المحرك', 'spec.Pump pressure': 'ضغط المضخة', 'spec.Coffee compatibility': 'توافق القهوة', 'spec.Brewing mode': 'وضع التحضير', 'spec.Body material': 'مادة الهيكل', 'spec.Rated voltage': 'الجهد المقنن', 'spec.Charging': 'الشحن', 'spec.Product size': 'حجم المنتج', 'spec.Gross weight': 'الوزن الإجمالي',
    'value.OEM available': 'يتوفر تصنيع OEM', 'value.OEM / private label available': 'يتوفر OEM وعلامة خاصة', 'value.Capsules and ground coffee': 'كبسولات وقهوة مطحونة', 'value.Hot and cold extraction': 'استخلاص ساخن وبارد', 'value.Plastic': 'بلاستيك', 'value.USB-C, approx. 4 hours': 'USB-C، حوالي 4 ساعات', 'colour.Black': 'أسود', 'colour.Silver Gray': 'رمادي فضي', 'colour.Olive Green': 'أخضر زيتوني', 'colour.Pink': 'وردي', 'colour.Dark Green': 'أخضر داكن', 'colour.Light Purple': 'بنفسجي فاتح',
  },
};
