// Generated by scripts/import-ironing-catalog.mjs. Do not edit manually.
import type {Product} from './products';

export const ironingCatalogProducts: Product[] = [
  {
    "slug": "shanwu-m8025",
    "name": "SHANWU STEAM BRUSH M8025",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8025.webp",
    "description": "SHANWU STEAM BRUSH. Model M8025.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Steam lock switch",
      "Safty: auto shut-off in 8 minutes when not used",
      "Soleplate: stainless steel plate",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8025"
      },
      {
        "label": "Product name",
        "value": "STEAM BRUSH"
      },
      {
        "label": "Specification 1",
        "value": "Steam lock switch"
      },
      {
        "label": "Specification 2",
        "value": "Safty: auto shut-off in 8 minutes when not used"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: stainless steel plate"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "350ml"
      },
      {
        "label": "Unit size",
        "value": "265x175x155mm"
      },
      {
        "label": "Soleplate size",
        "value": "142x78mm"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Water tank provides continuous steam",
        "value": "15 minutes"
      },
      {
        "label": "Steam ready time",
        "value": "30s"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "215x160x275mm"
      },
      {
        "label": "Carton Meas.",
        "value": "82.0x44.3x29.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "13/12Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-2800pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-5600pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-6300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8022",
    "name": "SHANWU STEAM BRUSH M8022",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8022.webp",
    "description": "SHANWU STEAM BRUSH. Model M8022.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Steam lock switch",
      "Safty: auto shut-off in 8 minutes when not used",
      "Soleplate: stainless steel plate",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8022"
      },
      {
        "label": "Product name",
        "value": "STEAM BRUSH"
      },
      {
        "label": "Specification 1",
        "value": "Steam lock switch"
      },
      {
        "label": "Specification 2",
        "value": "Safty: auto shut-off in 8 minutes when not used"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: stainless steel plate"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "350ml"
      },
      {
        "label": "Unit size",
        "value": "265x175x155mm"
      },
      {
        "label": "Soleplate size",
        "value": "142x78mm"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Water tank provides continuous steam",
        "value": "15 minutes"
      },
      {
        "label": "Steam ready time",
        "value": "30s"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "215x160x275mm"
      },
      {
        "label": "Carton Meas.",
        "value": "82.0x44.3x29.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "13/12Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-2800pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-5600pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-6300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8023",
    "name": "SHANWU STEAM BRUSH M8023",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8023.webp",
    "description": "SHANWU STEAM BRUSH. Model M8023.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Steam lock switch",
      "Safty: auto shut-off in 8 minutes when not used",
      "Soleplate: stainless steel plate",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8023"
      },
      {
        "label": "Product name",
        "value": "STEAM BRUSH"
      },
      {
        "label": "Specification 1",
        "value": "Steam lock switch"
      },
      {
        "label": "Specification 2",
        "value": "Safty: auto shut-off in 8 minutes when not used"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: stainless steel plate"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "350ml"
      },
      {
        "label": "Unit size",
        "value": "265x175x155mm"
      },
      {
        "label": "Soleplate size",
        "value": "142x78mm"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Water tank provides continuous steam",
        "value": "15 minutes"
      },
      {
        "label": "Steam ready time",
        "value": "30s"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "215x160x275mm"
      },
      {
        "label": "Carton Meas.",
        "value": "82.0x44.3x29.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "13/12Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-2800pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-5600pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-6300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8008",
    "name": "SHANWU ELECTRIC IRON M8008",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8008.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8008.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8008"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "500ml"
      },
      {
        "label": "Unit size",
        "value": "310x130x160mm"
      },
      {
        "label": "Soleplate size",
        "value": "236x130mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-35g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "320x135x170mm"
      },
      {
        "label": "Carton Meas.",
        "value": "69.5x32.8x35.5cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16/15Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3300pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-7100pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-8300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8006",
    "name": "SHANWU ELECTRIC IRON M8006",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8006.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8006.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Ceramic coating/Nano Ceramic coating/anodic oxidation",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8006"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Ceramic coating/Nano Ceramic coating/anodic oxidation"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "350ml"
      },
      {
        "label": "Unit size",
        "value": "300x125x160mm"
      },
      {
        "label": "Soleplate size",
        "value": "245x125mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-35g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "320x135x170mm"
      },
      {
        "label": "Carton Meas.",
        "value": "69.5x32.8x35.5cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16.8/16Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3300pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-7100pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-8300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8009",
    "name": "SHANWU ELECTRIC IRON M8009",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8009.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8009.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8009"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "450ml"
      },
      {
        "label": "Unit size",
        "value": "300x12.5x150mm"
      },
      {
        "label": "Soleplate size",
        "value": "240x12.5mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "315x125x159mm"
      },
      {
        "label": "Carton Meas.",
        "value": "65.5x32.6x34.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16/15Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3380pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-7500pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-8800pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8018",
    "name": "SHANWU ELECTRIC IRON M8018",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8018.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8018.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8018"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "500ml"
      },
      {
        "label": "Unit size",
        "value": "310x130x155mm"
      },
      {
        "label": "Soleplate size",
        "value": "236x130mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-35g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "320x135x170mm"
      },
      {
        "label": "Carton Meas.",
        "value": "69.5x32.8x35.5cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16/15Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3300pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-7100pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-8300pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8016",
    "name": "SHANWU ELECTRIC IRON M8016",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8016.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8016.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8016"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "500ml"
      },
      {
        "label": "Unit size",
        "value": "310x135x173mm"
      },
      {
        "label": "Soleplate size",
        "value": "247x135mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-35g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "320x140x190mm"
      },
      {
        "label": "Carton Meas.",
        "value": "71.8x32.8x39.6cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16/15KG"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3200pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-6400pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-6700pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8019",
    "name": "SHANWU ELECTRIC IRON M8019",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8019.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8019.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Optional features: anti-calc/anti-drip/auto shut-off",
      "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8019"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Optional features: anti-calc/anti-drip/auto shut-off"
      },
      {
        "label": "Specification 3",
        "value": "Soleplate: Non-Stick coating/Ceramic coating/Nano Ceramic coating"
      },
      {
        "label": "Specification 4",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 5",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-3200W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "450ml"
      },
      {
        "label": "Unit size",
        "value": "300x12.5x150mm"
      },
      {
        "label": "Soleplate size",
        "value": "240x12.5mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.8-1.0g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "315x125x159mm"
      },
      {
        "label": "Carton Meas.",
        "value": "65.5x32.6x34.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "16/15Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-3380pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-7500pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-8800pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8001",
    "name": "SHANWU ELECTRIC IRON M8001",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8001.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8001.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Dry/spray/steam/vertical burst of steam/self-cleaning",
      "Soleplate: Non-Stick teflon coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8001"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Specification 1",
        "value": "Dry/spray/steam/vertical burst of steam/self-cleaning"
      },
      {
        "label": "Specification 2",
        "value": "Soleplate: Non-Stick teflon coating"
      },
      {
        "label": "Specification 3",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 4",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-2000W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "250ml"
      },
      {
        "label": "Unit size",
        "value": "271x110x130mm"
      },
      {
        "label": "Soleplate size",
        "value": "215x110mm"
      },
      {
        "label": "Burst of steam rate",
        "value": "0.5-0.8g/time"
      },
      {
        "label": "Spray rate",
        "value": "0.5-0.8g/time"
      },
      {
        "label": "Continuous steam rate",
        "value": "10-20g/min"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "280x116x140mm"
      },
      {
        "label": "Carton Meas.",
        "value": "59.5x28.5x30.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "8.4/9.1Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-5280pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-11200pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-12800pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8002",
    "name": "SHANWU ELECTRIC IRON M8002",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8002.webp",
    "description": "SHANWU ELECTRIC IRON. Model M8002.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8002"
      },
      {
        "label": "Product name",
        "value": "ELECTRIC IRON"
      },
      {
        "label": "Power",
        "value": "800W-1000W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Unit size",
        "value": "250x102x122mm"
      },
      {
        "label": "Soleplate size",
        "value": "186x102mm"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "260x108x133mm"
      },
      {
        "label": "Carton Meas.",
        "value": "52.3x27.5x29.0cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "7.4/8.0Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-7040pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-14720pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-16560pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8021",
    "name": "SHANWU STEAM BRUSH M8021",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8021.webp",
    "description": "SHANWU STEAM BRUSH. Model M8021.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Steam lock switch",
      "Three-position steam switch",
      "Safty: auto shut-off in 8 minutes when not used",
      "Soleplate: stainless steel plate/tefon/ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8021"
      },
      {
        "label": "Product name",
        "value": "STEAM BRUSH"
      },
      {
        "label": "Specification 1",
        "value": "Steam lock switch"
      },
      {
        "label": "Specification 2",
        "value": "Three-position steam switch"
      },
      {
        "label": "Specification 3",
        "value": "Safty: auto shut-off in 8 minutes when not used"
      },
      {
        "label": "Specification 4",
        "value": "Soleplate: stainless steel plate/tefon/ceramic coating"
      },
      {
        "label": "Specification 5",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 6",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-2000W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "450ml"
      },
      {
        "label": "Unit size",
        "value": "170x110x280mm"
      },
      {
        "label": "Soleplate size",
        "value": "110x70mm"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Water tank provides continuous steam",
        "value": "10 minutes"
      },
      {
        "label": "Steam ready time",
        "value": "30s"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "205x130x306mm"
      },
      {
        "label": "Carton Meas.",
        "value": "67.0x31.5x42.5cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "11.5/10.5Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-2800pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-5950pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-7100pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  },
  {
    "slug": "shanwu-m8028",
    "name": "SHANWU STEAM BRUSH M8028",
    "category": "Home",
    "image": "/catalog/ironing-2026/shanwu-m8028.webp",
    "description": "SHANWU STEAM BRUSH. Model M8028.",
    "moq": "待补充",
    "price": "Wholesale price on request",
    "highlights": [
      "Steam lock switch",
      "Three-position steam switch",
      "Safty: auto shut-off in 8 minutes when not used",
      "Soleplate: stainless steel plate/tefon/ceramic coating",
      "High accurate temperature control",
      "Overheat safety protection circuit"
    ],
    "specs": [
      {
        "label": "Brand",
        "value": "SHANWU"
      },
      {
        "label": "Model",
        "value": "M8028"
      },
      {
        "label": "Product name",
        "value": "STEAM BRUSH"
      },
      {
        "label": "Specification 1",
        "value": "Steam lock switch"
      },
      {
        "label": "Specification 2",
        "value": "Three-position steam switch"
      },
      {
        "label": "Specification 3",
        "value": "Safty: auto shut-off in 8 minutes when not used"
      },
      {
        "label": "Specification 4",
        "value": "Soleplate: stainless steel plate/tefon/ceramic coating"
      },
      {
        "label": "Specification 5",
        "value": "High accurate temperature control"
      },
      {
        "label": "Specification 6",
        "value": "Overheat safety protection circuit"
      },
      {
        "label": "Power",
        "value": "1600W-2000W"
      },
      {
        "label": "Voltage",
        "value": "220-240V/100-127V"
      },
      {
        "label": "Frequency",
        "value": "50/60Hz"
      },
      {
        "label": "Water tank capacity",
        "value": "450ml"
      },
      {
        "label": "Unit size",
        "value": "170x110x280mm"
      },
      {
        "label": "Soleplate size",
        "value": "110x70mm"
      },
      {
        "label": "Continuous steam rate",
        "value": "15-30g/min"
      },
      {
        "label": "Water tank provides continuous steam",
        "value": "10 minutes"
      },
      {
        "label": "Steam ready time",
        "value": "30s"
      },
      {
        "label": "Packing details as follows",
        "value": "10pcs/Carton"
      },
      {
        "label": "Giftbox Size",
        "value": "205x130x306mm"
      },
      {
        "label": "Carton Meas.",
        "value": "67.0x31.5x42.5cm"
      },
      {
        "label": "G.W./N.W.",
        "value": "12.2/11.2Kgs"
      },
      {
        "label": "Loading quantity 1",
        "value": "20'-2800pcs"
      },
      {
        "label": "Loading quantity 2",
        "value": "40'-5950pcs"
      },
      {
        "label": "Loading quantity 3",
        "value": "40HQ-7100pcs"
      },
      {
        "label": "Company",
        "value": "宁波山雾科技有限公司"
      }
    ]
  }
];
